### ISSUE TITLE
Expected FPS for Segmentation Model

### ISSUE THREAD

**Issue by xclucas** [tirandazi/depthai-yolov8-segment#1]
Hello and thank you for consolidating your code here.

I've been trying to run this model on my device and have been following the related thread on the Luxonis forum. However, I haven't been able to find any information about the model performance. How much FPS am I supposed to be getting? Should I be seeing a CPU bottleneck in the decode step?

Thanks!

**Comment by tirandazi** [comment]
Hi @Reschivon,
One of the factors that might impact FPS might be the image resolution. Lower the image resolution, higher the FPS. But, I would suggest you to create a thread in the luxonis forum and get any additional support from the luxonis team regarding the inference speed or performance.
